run:
  timeout: 5m
  skip-dirs:
    - web/admin
    - testdata
linters:
  enable:
    - govet
    - gofmt
    - gofumpt
    - goimports
    - errcheck
    - staticcheck
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
