version: "3.9"

services:
  httpbin:
    image: mccutchen/go-httpbin:v2.11.1
    environment:
      PORT: 8080
    ports:
      - "9107:8080"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: yapi
      POSTGRES_PASSWORD: yapi
      POSTGRES_DB: yapi
    ports:
      - "9109:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "9108:6379"

volumes:
  postgres-data:
