version: "3.9"

services:
  httpbin:
    image: mccutchen/go-httpbin:v2.11.1
    environment:
      PORT: 8080
    ports:
      - "9107:8080"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: yapi
      POSTGRES_PASSWORD: yapi
      POSTGRES_DB: yapi
    ports:
      - "9109:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "9108:6379"

  gateway:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    env_file:
      - ../.env.local
    environment:
      GATEWAY_PORT: "8080"
      UPSTREAM_BASE_URL: "https://api.openai.com"
      DATABASE_DSN: "postgres://yapi:yapi@postgres:5432/yapi?sslmode=disable"
      REDIS_ADDR: "redis:6379"
      REDIS_CHANNEL: "rules:sync"
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - httpbin
      - postgres
      - redis

volumes:
  postgres-data:
